apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx256m
        image: rhdevelopers/backend:1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/api/backend
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        name: backend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/api/backend
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
