apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      version: v1
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
        - name: GATEWAY_SPRINGBOOTSVCURL
          value: hello-springboot
        - name: GATEWAY_MICROPROFILESVCURL
          value: hello-microprofile
        image: rhdevelopers/api-gateway:1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/actuator/health
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        name: api-gateway
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/actuator/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
