apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-microprofile
  labels:
    app: hello-microprofile
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-microprofile
      version: v1
  template:
    metadata:
      labels:
        app: hello-microprofile
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
        - name: GREETING_BACKENDSERVICEHOST
          value: backend
        image: rhdevelopers/hello-microprofile:1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/api/hello
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        name: hello-microprofile
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/api/hello
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
